---
title: "Decision Support Systems and Bussiness Intelligence - 2019"
author: "Lu Haibo"
output:
  html_document:
    df_print: paged
  tufte::tufte_book:
    citation_package: natbib
    latex_engine: xelatex
  tufte::tufte_handout:
    citation_package: natbib
    latex_engine: xelatex
  tufte::tufte_html: default
link-citations: yes
---

```{r setup, include=FALSE}
library(tufte)
# invalidate cache when the tufte version changes
knitr::opts_chunk$set(tidy = FALSE, cache.extra = packageVersion('tufte'))
options(htmltools.dir.version = FALSE)
```

## Lecture Notes

[Syllabus](lecture/0.syllabus.pdf)

1. [Overview](lecture/1.Overview.pdf), [Rmarkdown](lecture/1.Overview.Rmd)
2. [Linear Regression](lecture/2.LinearReg.pdf), [Rmarkdown](lecture/2.LinearReg.Rmd)
3. [Intro R](lecture/hadley_many_models.pdf), [Lecture Note](lecture/intro_r.html), [Rmarkdown](lecture/intro_r.Rmd)
4. [Classification](lecture/3.Classification.pdf), [Rmarkdown](lecture/3.Classification.Rmd)
5. [Linear_Model_Selection](lecture/5.Linear_Model_Selection.pdf), [Rmarkdown](lecture/5.Linear_Model_Selection.Rmd), [Resampling](lecture/4.Resampling.pdf)

## Homework

1. [03-04: Linear Regression](lecture/homework/homework1.pdf)
2. [03-11: Classification](lecture/homework/homework2.pdf)
3. [03-25: Linear Model Selection](lecture/mnist.R), [Data: Mnist](lecture/mnist.zip)

## Text and Readings

- [Business Intelligence and Analysis: Systems for Decision Support (10th)](book/Business_Intelligence_and_Analytics_Systems_for_Decision_10.pdf)
- [Data Mining For Bussiness Intelligence](book/DATA MINING For Bussiness Intelligence.zip)
- [R for Data Science](https://r4ds.had.co.nz/)
- [An Introduction to Statistical Learning with applications in R](book/An introduction to statistical learning with applications in R.pdf)
- [The Elements of Statistical Learning (Data Mining, Inference, and Prediction)](book/ESLII_print10.pdf)

## Software

- [R](https://www.r-project.org/)
- [RStudio](https://www.rstudio.com/)

##

- Email: sit_stat@163.com